# Generated by Django 6.0.3 on 2026-06-30 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('Chennai', 'Chennai'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Pune', 'Pune')], max_length=20)),
                ('state', models.CharField(choices=[('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Telangana', 'Telangana'), ('Maharashtra', 'Maharashtra')], max_length=20)),
                ('country', models.CharField(choices=[('India', 'India')], default='India', max_length=20)),
                ('pin', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='PIN must contain exactly 6 digits.', regex='^\\d{6}$')])),
                ('full_address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
