# Generated by Django 6.0.6 on 2026-07-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='eb_bill_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/eb_bill/'),
        ),
    ]
